### ISSUE TITLE
All input fields are uneditable.

### ISSUE THREAD

**Issue by kewab** [yaakapp/app#97]
### What happened?

```css
:not(a), :not(input):not(textarea), :not(input):not(textarea):after, :not(input):not(textarea):before {
  cursor: default;
  -webkit-user-select: none; 
  -moz-user-select: none;
  user-select: none;
}
```
`-webkit-user-select: none` This CSS causes the input field to be uneditable.

macOS: 12.4
Intel Core i5

### Version

2024.9.1

### What operating system are you on?

macOS
